For me, using LibXML instead of LibXml for the local FeedParser module name caused problems:
NameError: uninitialized constant FeedParser::LibXML::XML
	from /Users/jay/rfeedparser/lib/rfeedparser/libxml_parser.rb:22

So changing it back.